### ISSUE TITLE
Plugin with id 'com.android.application' not found

### ISSUE THREAD

**Issue by grayfallstown** [iVGeek/ItemDetection#1]
```

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\mk\IdeaProjects\java\myprojects\object-recognition\ItemDetection\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'ItemDetection'.
> Plugin with id 'com.android.application' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s

```

**Comment by iVGeek** [comment]
The error indicates that the Android Gradle Plugin `com.android.application` is missing or not properly configured in your project. Here's how to resolve it:

### Steps to Fix the Issue

1. **Verify Plugin Declaration in `build.gradle`**
   - Open the **root `build.gradle` file** in the project (not the one inside `app`).
   - Ensure the correct plugin is applied:
     ```gradle
     plugins {
         id 'com.android.application' version '8.1.0' apply false
     }
     ```
   - Replace `8.1.0` with the appropriate version for your Android Studio and Gradle setup.

2. **Check the `settings.gradle` File**
   - Ensure that the `settings.gradle` file references the correct module (e.g., `app`):
     ```gradle
     include ':app'
     ```

3. **Upgrade or Sync Gradle**
   - If the plugin is missing, update the Gradle version:
     - Go to **File > Project Structure > Project**.
     - Update the **Gradle version** and **Android plugin version** to match your Android Studio installation.

   - Alternatively, manually update the `gradle-wrapper.properties` file:
     ```properties
     distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-all.zip
     ```

4. **Ensure Gradle Plugin Dependency in `build.gradle`**
   - In the `dependencies` section of the **root `build.gradle` file**, ensure the Android Gradle Plugin is included:
     ```gradle
     classpath 'com.android.tools.build:gradle:8.1.0'
     ```

5. **Sync Project**
   - Click **Sync Project with Gradle Files** in Android Studio (usually a button at the top-right corner).

6. **Reinstall Dependencies (Optional)**
   - Delete the `.gradle` and `build` folders in your project directory to force a clean rebuild.

7. **Run the Build Again**
   - Run `./gradlew build` in the terminal to verify the build works without errors.


If the issue persists, share the contents of your `build.gradle` files, and I can provide more specific guidance.

**Comment by grayfallstown** [comment]
thx
